/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { RecordLabelService } from "../recordLabel.service";
import { RecordLabelCreateInput } from "./RecordLabelCreateInput";
import { RecordLabelWhereInput } from "./RecordLabelWhereInput";
import { RecordLabelWhereUniqueInput } from "./RecordLabelWhereUniqueInput";
import { RecordLabelFindManyArgs } from "./RecordLabelFindManyArgs";
import { RecordLabelUpdateInput } from "./RecordLabelUpdateInput";
import { RecordLabel } from "./RecordLabel";

export class RecordLabelGrpcControllerBase {
  constructor(protected readonly service: RecordLabelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RecordLabel })
  @GrpcMethod("RecordLabelService", "createRecordLabel")
  async createRecordLabel(
    @common.Body() data: RecordLabelCreateInput
  ): Promise<RecordLabel> {
    return await this.service.createRecordLabel({
      data: {
        ...data,

        virtualArtist: data.virtualArtist
          ? {
              connect: data.virtualArtist,
            }
          : undefined,
      },
      select: {
        analytics: true,
        createdAt: true,
        id: true,
        name: true,
        promotions: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [RecordLabel] })
  @ApiNestedQuery(RecordLabelFindManyArgs)
  @GrpcMethod("RecordLabelService", "recordLabels")
  async recordLabels(@common.Req() request: Request): Promise<RecordLabel[]> {
    const args = plainToClass(RecordLabelFindManyArgs, request.query);
    return this.service.recordLabels({
      ...args,
      select: {
        analytics: true,
        createdAt: true,
        id: true,
        name: true,
        promotions: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RecordLabel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RecordLabelService", "recordLabel")
  async recordLabel(
    @common.Param() params: RecordLabelWhereUniqueInput
  ): Promise<RecordLabel | null> {
    const result = await this.service.recordLabel({
      where: params,
      select: {
        analytics: true,
        createdAt: true,
        id: true,
        name: true,
        promotions: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RecordLabel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RecordLabelService", "updateRecordLabel")
  async updateRecordLabel(
    @common.Param() params: RecordLabelWhereUniqueInput,
    @common.Body() data: RecordLabelUpdateInput
  ): Promise<RecordLabel | null> {
    try {
      return await this.service.updateRecordLabel({
        where: params,
        data: {
          ...data,

          virtualArtist: data.virtualArtist
            ? {
                connect: data.virtualArtist,
              }
            : undefined,
        },
        select: {
          analytics: true,
          createdAt: true,
          id: true,
          name: true,
          promotions: true,
          updatedAt: true,

          virtualArtist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RecordLabel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RecordLabelService", "deleteRecordLabel")
  async deleteRecordLabel(
    @common.Param() params: RecordLabelWhereUniqueInput
  ): Promise<RecordLabel | null> {
    try {
      return await this.service.deleteRecordLabel({
        where: params,
        select: {
          analytics: true,
          createdAt: true,
          id: true,
          name: true,
          promotions: true,
          updatedAt: true,

          virtualArtist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
