/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { MusicChallengeService } from "../musicChallenge.service";
import { MusicChallengeCreateInput } from "./MusicChallengeCreateInput";
import { MusicChallengeWhereInput } from "./MusicChallengeWhereInput";
import { MusicChallengeWhereUniqueInput } from "./MusicChallengeWhereUniqueInput";
import { MusicChallengeFindManyArgs } from "./MusicChallengeFindManyArgs";
import { MusicChallengeUpdateInput } from "./MusicChallengeUpdateInput";
import { MusicChallenge } from "./MusicChallenge";

export class MusicChallengeGrpcControllerBase {
  constructor(protected readonly service: MusicChallengeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MusicChallenge })
  @GrpcMethod("MusicChallengeService", "createMusicChallenge")
  async createMusicChallenge(
    @common.Body() data: MusicChallengeCreateInput
  ): Promise<MusicChallenge> {
    return await this.service.createMusicChallenge({
      data: {
        ...data,

        virtualArtist: data.virtualArtist
          ? {
              connect: data.virtualArtist,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        rewards: true,
        title: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [MusicChallenge] })
  @ApiNestedQuery(MusicChallengeFindManyArgs)
  @GrpcMethod("MusicChallengeService", "musicChallenges")
  async musicChallenges(
    @common.Req() request: Request
  ): Promise<MusicChallenge[]> {
    const args = plainToClass(MusicChallengeFindManyArgs, request.query);
    return this.service.musicChallenges({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        rewards: true,
        title: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MusicChallenge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("MusicChallengeService", "musicChallenge")
  async musicChallenge(
    @common.Param() params: MusicChallengeWhereUniqueInput
  ): Promise<MusicChallenge | null> {
    const result = await this.service.musicChallenge({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        rewards: true,
        title: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MusicChallenge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("MusicChallengeService", "updateMusicChallenge")
  async updateMusicChallenge(
    @common.Param() params: MusicChallengeWhereUniqueInput,
    @common.Body() data: MusicChallengeUpdateInput
  ): Promise<MusicChallenge | null> {
    try {
      return await this.service.updateMusicChallenge({
        where: params,
        data: {
          ...data,

          virtualArtist: data.virtualArtist
            ? {
                connect: data.virtualArtist,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          rewards: true,
          title: true,
          updatedAt: true,

          virtualArtist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MusicChallenge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("MusicChallengeService", "deleteMusicChallenge")
  async deleteMusicChallenge(
    @common.Param() params: MusicChallengeWhereUniqueInput
  ): Promise<MusicChallenge | null> {
    try {
      return await this.service.deleteMusicChallenge({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          rewards: true,
          title: true,
          updatedAt: true,

          virtualArtist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
