/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { AiStudioService } from "../aiStudio.service";
import { AiStudioCreateInput } from "./AiStudioCreateInput";
import { AiStudioWhereInput } from "./AiStudioWhereInput";
import { AiStudioWhereUniqueInput } from "./AiStudioWhereUniqueInput";
import { AiStudioFindManyArgs } from "./AiStudioFindManyArgs";
import { AiStudioUpdateInput } from "./AiStudioUpdateInput";
import { AiStudio } from "./AiStudio";

export class AiStudioGrpcControllerBase {
  constructor(protected readonly service: AiStudioService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AiStudio })
  @GrpcMethod("AiStudioService", "createAiStudio")
  async createAiStudio(
    @common.Body() data: AiStudioCreateInput
  ): Promise<AiStudio> {
    return await this.service.createAiStudio({
      data: {
        ...data,

        virtualArtist: data.virtualArtist
          ? {
              connect: data.virtualArtist,
            }
          : undefined,
      },
      select: {
        composition: true,
        createdAt: true,
        id: true,
        mixing: true,
        production: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AiStudio] })
  @ApiNestedQuery(AiStudioFindManyArgs)
  @GrpcMethod("AiStudioService", "aiStudios")
  async aiStudios(@common.Req() request: Request): Promise<AiStudio[]> {
    const args = plainToClass(AiStudioFindManyArgs, request.query);
    return this.service.aiStudios({
      ...args,
      select: {
        composition: true,
        createdAt: true,
        id: true,
        mixing: true,
        production: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AiStudio })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AiStudioService", "aiStudio")
  async aiStudio(
    @common.Param() params: AiStudioWhereUniqueInput
  ): Promise<AiStudio | null> {
    const result = await this.service.aiStudio({
      where: params,
      select: {
        composition: true,
        createdAt: true,
        id: true,
        mixing: true,
        production: true,
        updatedAt: true,

        virtualArtist: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AiStudio })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AiStudioService", "updateAiStudio")
  async updateAiStudio(
    @common.Param() params: AiStudioWhereUniqueInput,
    @common.Body() data: AiStudioUpdateInput
  ): Promise<AiStudio | null> {
    try {
      return await this.service.updateAiStudio({
        where: params,
        data: {
          ...data,

          virtualArtist: data.virtualArtist
            ? {
                connect: data.virtualArtist,
              }
            : undefined,
        },
        select: {
          composition: true,
          createdAt: true,
          id: true,
          mixing: true,
          production: true,
          updatedAt: true,

          virtualArtist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AiStudio })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AiStudioService", "deleteAiStudio")
  async deleteAiStudio(
    @common.Param() params: AiStudioWhereUniqueInput
  ): Promise<AiStudio | null> {
    try {
      return await this.service.deleteAiStudio({
        where: params,
        select: {
          composition: true,
          createdAt: true,
          id: true,
          mixing: true,
          production: true,
          updatedAt: true,

          virtualArtist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
