/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { VoiceCustomizationService } from "../voiceCustomization.service";
import { VoiceCustomizationCreateInput } from "./VoiceCustomizationCreateInput";
import { VoiceCustomizationWhereInput } from "./VoiceCustomizationWhereInput";
import { VoiceCustomizationWhereUniqueInput } from "./VoiceCustomizationWhereUniqueInput";
import { VoiceCustomizationFindManyArgs } from "./VoiceCustomizationFindManyArgs";
import { VoiceCustomizationUpdateInput } from "./VoiceCustomizationUpdateInput";
import { VoiceCustomization } from "./VoiceCustomization";
import { VirtualArtistFindManyArgs } from "../../virtualArtist/base/VirtualArtistFindManyArgs";
import { VirtualArtist } from "../../virtualArtist/base/VirtualArtist";
import { VirtualArtistWhereUniqueInput } from "../../virtualArtist/base/VirtualArtistWhereUniqueInput";

export class VoiceCustomizationGrpcControllerBase {
  constructor(protected readonly service: VoiceCustomizationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VoiceCustomization })
  @GrpcMethod("VoiceCustomizationService", "createVoiceCustomization")
  async createVoiceCustomization(
    @common.Body() data: VoiceCustomizationCreateInput
  ): Promise<VoiceCustomization> {
    return await this.service.createVoiceCustomization({
      data: data,
      select: {
        aiGeneratedVoice: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        voiceClonedFrom: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [VoiceCustomization] })
  @ApiNestedQuery(VoiceCustomizationFindManyArgs)
  @GrpcMethod("VoiceCustomizationService", "voiceCustomizations")
  async voiceCustomizations(
    @common.Req() request: Request
  ): Promise<VoiceCustomization[]> {
    const args = plainToClass(VoiceCustomizationFindManyArgs, request.query);
    return this.service.voiceCustomizations({
      ...args,
      select: {
        aiGeneratedVoice: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        voiceClonedFrom: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VoiceCustomization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("VoiceCustomizationService", "voiceCustomization")
  async voiceCustomization(
    @common.Param() params: VoiceCustomizationWhereUniqueInput
  ): Promise<VoiceCustomization | null> {
    const result = await this.service.voiceCustomization({
      where: params,
      select: {
        aiGeneratedVoice: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        voiceClonedFrom: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VoiceCustomization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("VoiceCustomizationService", "updateVoiceCustomization")
  async updateVoiceCustomization(
    @common.Param() params: VoiceCustomizationWhereUniqueInput,
    @common.Body() data: VoiceCustomizationUpdateInput
  ): Promise<VoiceCustomization | null> {
    try {
      return await this.service.updateVoiceCustomization({
        where: params,
        data: data,
        select: {
          aiGeneratedVoice: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          voiceClonedFrom: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VoiceCustomization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("VoiceCustomizationService", "deleteVoiceCustomization")
  async deleteVoiceCustomization(
    @common.Param() params: VoiceCustomizationWhereUniqueInput
  ): Promise<VoiceCustomization | null> {
    try {
      return await this.service.deleteVoiceCustomization({
        where: params,
        select: {
          aiGeneratedVoice: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          voiceClonedFrom: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/virtualArtists")
  @ApiNestedQuery(VirtualArtistFindManyArgs)
  @GrpcMethod("VoiceCustomizationService", "findManyVirtualArtists")
  async findManyVirtualArtists(
    @common.Req() request: Request,
    @common.Param() params: VoiceCustomizationWhereUniqueInput
  ): Promise<VirtualArtist[]> {
    const query = plainToClass(VirtualArtistFindManyArgs, request.query);
    const results = await this.service.findVirtualArtists(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        genre: true,
        id: true,
        name: true,
        updatedAt: true,

        voiceCustomization: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/virtualArtists")
  @GrpcMethod("VoiceCustomizationService", "connectVirtualArtists")
  async connectVirtualArtists(
    @common.Param() params: VoiceCustomizationWhereUniqueInput,
    @common.Body() body: VirtualArtistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      virtualArtists: {
        connect: body,
      },
    };
    await this.service.updateVoiceCustomization({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/virtualArtists")
  @GrpcMethod("VoiceCustomizationService", "updateVirtualArtists")
  async updateVirtualArtists(
    @common.Param() params: VoiceCustomizationWhereUniqueInput,
    @common.Body() body: VirtualArtistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      virtualArtists: {
        set: body,
      },
    };
    await this.service.updateVoiceCustomization({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/virtualArtists")
  @GrpcMethod("VoiceCustomizationService", "disconnectVirtualArtists")
  async disconnectVirtualArtists(
    @common.Param() params: VoiceCustomizationWhereUniqueInput,
    @common.Body() body: VirtualArtistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      virtualArtists: {
        disconnect: body,
      },
    };
    await this.service.updateVoiceCustomization({
      where: params,
      data,
      select: { id: true },
    });
  }
}
